name: API Automation CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright API tests
        env:
          BASE_URL: https://jsonplaceholder.typicode.com
        run: npm run test:api

      - name: Run Newman collection
        run: |
          mkdir -p reports/newman
          npx newman run postman/CRUD_VAL.postman_collection.json \
            --env-var base_url=https://jsonplaceholder.typicode.com/posts \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/newman/newman-report.html
          ls -l reports/newman
          ls -R reports

      - name: Upload Newman report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/newman
